name: Reverse Docs Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: reverse-docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 (with Maven cache)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Show Java & Maven
        shell: bash
        run: |
          set -Eeuo pipefail
          java -version
          ./mvnw -v

      # Build & package
      - name: Build (skip tests)
        shell: bash
        run: |
          set -Eeuo pipefail
          ./mvnw -B -DskipTests package

      - name: Resolve JAR path
        id: jar
        shell: bash
        run: |
          set -Eeuo pipefail
          JAR_FILE="$(find target -maxdepth 1 -type f -name '*.jar' ! -name '*-sources.jar' ! -name '*-javadoc.jar' | head -n 1 || true)"
          if [ -z "${JAR_FILE:-}" ]; then
            echo "No runnable JAR found in target/"
            ls -l target || true
            exit 1
          fi
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
          echo "Found: $JAR_FILE"

      # Run app
      - name: Start app (background)
        shell: bash
        run: |
          set -Eeuo pipefail
          nohup java -jar "$JAR_FILE" \
            --server.port=9966 \
            --server.servlet.context-path=/petclinic \
            --spring.profiles.active=h2,spring-data-jpa \
            --management.endpoints.web.exposure.include=health,info \
            > target/app.log 2>&1 &
          echo $! > target/petclinic.pid
          echo "PID: $(cat target/petclinic.pid)"

      # Health check
      - name: Wait for health
        shell: bash
        run: |
          set -Eeuo pipefail
          urls=(
            http://localhost:9966/petclinic/actuator/health
            http://127.0.0.1:9966/petclinic/actuator/health
            http://localhost:9966/actuator/health
            http://localhost:8080/actuator/health
          )
          for i in $(seq 1 120); do
            for u in "${urls[@]}"; do
              if curl -fsS -4 "$u" >/dev/null; then
                echo "App is up: $u"
                echo "HEALTH_URL=$u" >> $GITHUB_ENV
                exit 0
              fi
            done
            if [ $((i%10)) -eq 0 ]; then
              echo "---- tail app.log (last 120 lines) ----"
              tail -n 120 target/app.log || true
              echo "---- listening ports ----"
              (command -v ss >/dev/null && ss -lptn || lsof -i :9966 || true)
            fi
            sleep 2
          done
          echo "App failed to become healthy within timeout"
          tail -n 200 target/app.log || true
          (command -v ss >/dev/null && ss -lptn || true)
          exit 1

      # Fetch OpenAPI
      - name: Fetch OpenAPI (JSON/YAML)
        shell: bash
        run: |
          set -Eeuo pipefail
          JSON_URL="${OPENAPI_JSON_URL:-http://localhost:9966/petclinic/v3/api-docs}"
          YAML_URL="${OPENAPI_YAML_URL:-http://localhost:9966/petclinic/v3/api-docs.yaml}"
          mkdir -p target/openapi
          echo "Try JSON: $JSON_URL"
          if curl --fail --silent --show-error "$JSON_URL" -o target/openapi/openapi.json; then
            echo "Saved openapi.json"
          else
            echo "JSON endpoint not found (continuing)"
          fi
          echo "Try YAML: $YAML_URL"
          if curl --fail --silent --show-error "$YAML_URL" -o target/openapi/openapi.yaml; then
            echo "Saved openapi.yaml"
          else
            echo "YAML endpoint not found (continuing)"
          fi
          ls -l target/openapi || true

      # Sanitize OpenAPI (fix invalid fields)
      - name: Sanitize OpenAPI (fix invalid fields)
        shell: bash
        run: |
          set -Eeuo pipefail
          if [ -f target/openapi/openapi.json ]; then
            tmp="$(mktemp)"
            jq '
              if (.info? and .info.license? and .info.license.extensions?) then
                .info.license |= (. + {"x-extensions": .extensions} | del(.extensions))
              else . end
            ' target/openapi/openapi.json > "$tmp" && mv "$tmp" target/openapi/openapi.json
            echo "Sanitized: moved info.license.extensions -> info.license.x-extensions"
          else
            echo "No openapi.json to sanitize (skipping)"
          fi

      # Ensure both JSON and YAML specs (no heredoc)
      - name: Ensure both JSON and YAML specs
        shell: bash
        run: |
          set -Eeuo pipefail
          python3 -m pip install --user PyYAML >/dev/null 2>&1 || true
          if [ -f target/openapi/openapi.json ] && [ ! -f target/openapi/openapi.yaml ]; then
            python3 -c "import json,yaml; d='target/openapi/openapi.json'; y='target/openapi/openapi.yaml'; data=json.load(open(d)); yaml.safe_dump(data, open(y,'w'), sort_keys=False); print('Created openapi.yaml from json')"
          elif [ -f target/openapi/openapi.yaml ] && [ ! -f target/openapi/openapi.json ]; then
            python3 -c "import json,yaml; y='target/openapi/openapi.yaml'; d='target/openapi/openapi.json'; data=yaml.safe_load(open(y)); json.dump(data, open(d,'w'), indent=2); print('Created openapi.json from yaml')"
          else
            echo "Both or neither present; no conversion"
          fi

      # OpenAPI -> HTML docs
      - name: Install OpenAPI Generator CLI
        shell: bash
        run: |
          set -Eeuo pipefail
          curl -sL https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.7.0/openapi-generator-cli-7.7.0.jar -o openapi-generator-cli.jar

      - name: Generate HTML API docs
        if: always()
        shell: bash
        run: |
          set -Eeuo pipefail
          mkdir -p target/api-docs
          if [ -f target/openapi/openapi.json ]; then
            java -jar openapi-generator-cli.jar generate \
              -i target/openapi/openapi.json \
              -g html2 \
              --skip-validate-spec \
              -o target/api-docs/json || true
          fi
          if [ -f target/openapi/openapi.yaml ]; then
            java -jar openapi-generator-cli.jar generate \
              -i target/openapi/openapi.yaml \
              -g html2 \
              --skip-validate-spec \
              -o target/api-docs/yaml || true
          fi

      # jdeps seed
      - name: Extract dependency graph (jdeps)
        shell: bash
        run: |
          set -Eeuo pipefail
          jdeps -q --multi-release 17 -recursive -verbose:class "$JAR_FILE" > target/jdeps.txt || true

      # Inspect target
      - name: Inspect target
        if: always()
        shell: bash
        run: |
          set -Eeuo pipefail
          echo "---- target ----"; ls -al target || true
          echo "---- openapi ----"; ls -al target/openapi || true
          echo "---- api-docs/json ----"; ls -al target/api-docs/json || true
          echo "---- api-docs/yaml ----"; ls -al target/api-docs/yaml || true

      # Ensure artifact bundle
      - name: Ensure artifact bundle
        if: always()
        shell: bash
        run: |
          set -Eeuo pipefail
          mkdir -p target/_meta
          {
            echo "Reverse Docs Artifact"
            date -u
            echo "Jar: ${JAR_FILE:-N/A}"
            echo "Health URL: ${HEALTH_URL:-N/A}"
          } > target/_meta/README.txt
          if [ ! -f target/app.log ]; then
            echo "app.log not found - app may not have started or logs redirected elsewhere" > target/app.log
          fi

      # Upload artifacts
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reverse-docs-artifacts
          path: |
            target/openapi/**
            target/api-docs/**
            target/jdeps.txt
            target/app.log
            target/site/**
            target/surefire-reports/**
            target/_meta/**
          if-no-files-found: warn
          retention-days: 14

      - name: Stop app
        if: always()
        shell: bash
        run: |
          set -Eeuo pipefail
          if [ -f target/petclinic.pid ]; then
            kill $(cat target/petclinic.pid) || true
          fi

  # Deploy to GitHub Pages (main/master push에서만)
  deploy-pages:
    needs: build-test-docs
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Configure Pages (auto enable)
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: reverse-docs-artifacts
          path: ./_artifacts

      - name: Prepare site
        shell: bash
        run: |
          set -Eeuo pipefail
          mkdir -p public

          # Copy html2 docs into subfolders
          if [ -d _artifacts/target/api-docs/json ]; then
            mkdir -p public/docs-json
            cp -r _artifacts/target/api-docs/json/* public/docs-json/
          fi
          if [ -d _artifacts/target/api-docs/yaml ]; then
            mkdir -p public/docs-yaml
            cp -r _artifacts/target/api-docs/yaml/* public/docs-yaml/
          fi

          # Copy OpenAPI specs
          mkdir -p public/openapi
          if [ -d _artifacts/target/openapi ]; then
            cp -r _artifacts/target/openapi/* public/openapi/ || true
          fi

          # Build index.html with only existing links
          has_json_docs=false; has_yaml_docs=false; has_yaml=false; has_json=false
          [ -f public/docs-json/index.html ] && has_json_docs=true
          [ -f public/docs-yaml/index.html ] && has_yaml_docs=true
          [ -f public/openapi/openapi.yaml ] && has_yaml=true
          [ -f public/openapi/openapi.json ] && has_json=true

          printf '%s\n' '<!doctype html><meta charset="utf-8"><title>Reverse Docs</title>' > public/index.html
          printf '%s\n' '<h1>Reverse Docs</h1>' >> public/index.html
          printf '%s\n' '<ul>' >> public/index.html
          $has_json_docs && printf '%s\n' '  <li><a href="./docs-json/index.html">API Docs (html2, from JSON)</a></li>' >> public/index.html
          $has_yaml_docs && printf '%s\n' '  <li><a href="./docs-yaml/index.html">API Docs (html2, from YAML)</a></li>' >> public/index.html
          $has_yaml && printf '%s\n' '  <li><a href="./openapi/openapi.yaml">openapi.yaml</a></li>' >> public/index.html
          $has_json && printf '%s\n' '  <li><a href="./openapi/openapi.json">openapi.json</a></li>' >> public/index.html
          printf '%s\n' '</ul>' >> public/index.html

          echo "Public dir contents:"; find public -maxdepth 2 -type f -print

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
